(()=>{
const state={runtime:{tasks:[],agents:[],toolExecutions:[],claims:[],waits:[],dispatches:[]},events:[],infra:null,auto:true};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const send=(action,payload={})=>chrome.webview.postMessage({action,...payload});
const arr=v=>Array.isArray(v)?v:[];
const json=v=>JSON.stringify(v??{},null,2);
const time=v=>{if(!v)return'-';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('zh-TW',{hour12:false,month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'})};
const short=(v,n=100)=>String(v??'').length>n?String(v).slice(0,n)+'…':String(v??'');
const badge=s=>`<span class="badge ${esc(String(s||'unknown').toLowerCase())}">${esc(s||'unknown')}</span>`;
const terminal=s=>['completed','failed','cancelled','blocked','interrupted','stale','ended','released','offline'].includes(String(s||'').toLowerCase());
function preview(v){if(v&&typeof v==='object'&&!Array.isArray(v)&&Object.hasOwn(v,'preview'))return String(v.preview);if(Array.isArray(v))return v.join(', ');if(v&&typeof v==='object')return JSON.stringify(v);return String(v??'')}
function detail(title,value,open=false){return `<details class="raw"${open?' open':''}><summary>${esc(title)}</summary><pre>${esc(typeof value==='string'?value:json(value))}</pre></details>`}
function scope(label,values){const items=arr(values);return `<div class="scope"><span>${esc(label)}</span>${items.length?`<ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<em>未指定</em>'}</div>`}

function renderInfrastructure(){const i=state.infra||{},m=i.mcp||{},cf=i.cloudflare||{},co=i.connector||{},active=cf.active||{};const mcpClass=m.running?'ok':'bad',cfClass=cf.running?'ok':'bad',connClass=co.matchesPublic?'ok':'warn';$('#infrastructure').innerHTML=`<article class="infra-card ${mcpClass}"><div class="infra-head"><strong>ProjectsMCP</strong>${badge(m.running?'running':'offline')}</div><div class="infra-main">${m.running?'SSE READY':'NOT READY'}</div><dl><dt>PID</dt><dd class="mono">${esc(m.listenerPid??'-')}</dd><dt>Port</dt><dd>${esc(m.port??'-')}</dd><dt>Local SSE</dt><dd class="mono">${esc(m.localSseUrl||'-')}</dd></dl></article><article class="infra-card ${cfClass}"><div class="infra-head"><strong>Cloudflare Tunnel</strong>${badge(cf.running?'running':'offline')}</div><div class="infra-main">${cf.running?'PROCESS RUNNING':'NOT RUNNING'}</div><dl><dt>Matched profile</dt><dd>${esc(active.profile||'-')}</dd><dt>PID</dt><dd>${esc(active.pid??'-')}</dd><dt>Hostname</dt><dd class="mono">${esc(active.hostname||'-')}</dd></dl></article><article class="infra-card ${connClass}"><div class="infra-head"><strong>Connector Config</strong>${badge(co.matchesPublic?'completed':'conflict')}</div><div class="infra-main">${co.matchesPublic?'CONFIG MATCHED':'CHECK CONFIG'}</div><dl><dt>Public SSE</dt><dd class="mono">${esc(co.publicSseUrl||'-')}</dd><dt>Configured connector</dt><dd class="mono">${esc(co.connectorEndpoint||'-')}</dd><dt>Verification</dt><dd>${esc(co.verification||'configuration_only')}</dd></dl></article>`}
function summary(){const t=arr(state.runtime.tasks),x=arr(state.runtime.toolExecutions),d=arr(state.runtime.dispatches);const activeTasks=t.filter(x=>!terminal(x.status)&&x.status!=='unknown').length,activeTools=x.filter(x=>x.status==='running').length,done=[...t,...x].filter(x=>terminal(x.status)).length,failed=[...t,...x,d].filter(x=>x.status==='failed').length;const values=[['Current work',activeTasks+activeTools,''],['Running tasks',t.filter(x=>x.status==='running').length,''],['Live MCP calls',activeTools,''],['A2A dispatch',d.filter(x=>['accepted','initializing','sending'].includes(x.status)).length,''],['Recently ended',done,''],['Failures',failed,failed?'bad':'']];$('#summary').innerHTML=values.map(([k,v,cl])=>`<div class="metric ${cl}"><div class="metric-label">${k}</div><div class="metric-value">${v}</div></div>`).join('')}
function renderRuntimeHealth(){const h=state.runtime.executionRuntimeHealth||{},rate=h.successRate==null?'-':`${(Number(h.successRate)*100).toFixed(1)}%`,cards=[['Success rate',rate],['Commands',h.total??0],['Timeouts',h.timeouts??0],['Auto recovery',h.recoveries??0],['Known issues prevented',h.knownIssuesPrevented??0],['Process trees killed',h.processTreesTerminated??0]];$('#runtimeHealthScope').textContent=h.scope==='retained_command_tool_executions'?`retained ${h.total??0}`:'no data';$('#runtimeHealth').innerHTML=cards.map(([label,value])=>`<article class="runtime-health-card"><div class="label">${esc(label)}</div><div class="value">${esc(value)}</div></article>`).join('');const classifications=arr(h.classifications),rules=arr(h.knownIssueRules);$('#runtimeClassifications').innerHTML=`<h3>Failure / Result classifications</h3>${classifications.length?classifications.map(x=>`<div class="runtime-health-row"><span class="mono">${esc(x.code)}</span><strong>${esc(x.count)}</strong></div>`).join(''):'<div class="muted">尚無 command classification telemetry。</div>'}`;$('#runtimeKnownIssues').innerHTML=`<h3>Known Issues prevention hits</h3>${rules.length?rules.map(x=>`<div class="runtime-health-row"><span class="mono">${esc(x.ruleId)}</span><strong>${esc(x.count)}</strong></div>`).join(''):'<div class="muted">目前保留範圍內尚無預防命中。</div>'}`}
function toolDescription(x){const p=x.parameters||{},bits=[];if(p.project)bits.push(`project=${preview(p.project)}`);if(p.path)bits.push(`path=${preview(p.path)}`);if(p.working_path)bits.push(`working_path=${preview(p.working_path)}`);if(p.cwd)bits.push(`cwd=${preview(p.cwd)}`);if(p.command)bits.push(`command=${preview(p.command)}`);if(p.old_text)bits.push(`old_text=${preview(p.old_text)}`);if(p.new_text)bits.push(`new_text=${preview(p.new_text)}`);return bits.length?bits.join(' · '):Object.keys(p).length?Object.entries(p).slice(0,4).map(([k,v])=>`${k}=${preview(v)}`).join(' · '):'無參數'}
function invocationFields(parameters){const p=parameters||{},priority=['project','path','working_path','source_path','cwd','command','old_text','new_text','objective'];const keys=[...priority.filter(k=>Object.hasOwn(p,k)),...Object.keys(p).filter(k=>!priority.includes(k))];return keys.length?`<dl class="invocation-fields">${keys.map(k=>`<dt>${esc(k)}</dt><dd${['command','old_text','new_text','objective'].includes(k)?' class="preline"':''}>${esc(preview(p[k]))}</dd>`).join('')}</dl>`:'<div class="muted">此工具沒有結構化參數。</div>'}
function correlationMeta(x){return `<span class="mono">boot ${esc(x.bootId||'-')}</span><span class="mono">run ${esc(x.runId||'-')}</span><span class="mono">trace ${esc(x.traceId||'-')}</span><span class="mono">span ${esc(x.spanId||'-')}</span><span class="mono">parent ${esc(x.parentSpanId||'-')}</span>`}
function traceStep(step){const x=step.item,label=step.kind==='tool'?'MCP TOOL':step.kind==='task'?'TASK':'DISPATCH',name=step.kind==='tool'?(x.tool||x.requestId):step.kind==='task'?(x.objective||x.taskId):(x.objective||x.dispatchId),identifier=step.kind==='tool'?x.requestId:step.kind==='task'?x.taskId:x.dispatchId;return `<div class="trace-step ${esc(step.kind)}"><div class="trace-rail"><span></span></div><div class="trace-step-body"><div class="trace-step-head"><span class="kind">${label}</span>${badge(x.status)}</div><strong>${esc(short(name||'unnamed step',180))}</strong><div class="meta"><span class="mono">${esc(identifier||'-')}</span><span>${esc(time(step.at))}</span><span>${esc(x.backend||x.agentId||x.assignedTo||'')}</span></div><div class="trace-ids">${correlationMeta(x)}</div>${step.kind==='tool'?invocationFields(x.parameters):''}${step.kind==='dispatch'&&x.dispatchPrompt?detail('實際送出的 dispatch prompt',x.dispatchPrompt):''}</div></div>`}
function renderTraces(){const records=[];arr(state.runtime.toolExecutions).forEach(item=>records.push({kind:'tool',item,at:item.startedAt||item.endedAt||''}));arr(state.runtime.tasks).forEach(item=>records.push({kind:'task',item,at:item.startedAt||item.queuedAt||item.updatedAt||''}));arr(state.runtime.dispatches).forEach(item=>records.push({kind:'dispatch',item,at:item.updatedAt||''}));const groups=new Map;for(const record of records){const x=record.item,correlated=x.traceId||x.runId,key=x.traceId?`trace:${x.traceId}`:x.runId?`run:${x.runId}`:`uncorrelated:${record.kind}:${x.requestId||x.taskId||x.dispatchId||Math.random()}`;if(!groups.has(key))groups.set(key,{key,correlated:!!correlated,steps:[]});groups.get(key).steps.push(record)}const items=[...groups.values()].map(group=>{group.steps.sort((a,b)=>String(a.at||'').localeCompare(String(b.at||'')));group.root=group.steps.find(step=>step.kind==='tool');group.at=group.steps.reduce((latest,step)=>String(step.at||'')>latest?String(step.at||''):latest,'');return group}).sort((a,b)=>b.at.localeCompare(a.at)).slice(0,80);$('#traceCount').textContent=items.length;$('#traces').innerHTML=items.length?items.map(group=>{const root=group.root&&group.root.item,anchor=root||group.steps[0].item,title=root?`Root MCP tool · ${root.tool||'unknown'}`:group.correlated?'Correlated internal work · root MCP record not visible':'Transport boundary / uncorrelated work',note=root?'Nested steps below share emitted trace/run correlation.':group.correlated?'A trace/run token exists, but the root tool is outside the retained state window. No relationship beyond that token is inferred.':'No traceId or runId was emitted. This may be new work after an external Agent/Connector boundary; A0 intentionally does not guess a parent trace.';return `<article class="trace-card ${group.correlated?'':'uncorrelated'}"><div class="trace-head"><div><div class="route">Execution Trace</div><h3>${esc(title)}</h3><p>${esc(note)}</p></div>${badge(root?root.status:(group.correlated?'correlated':'uncorrelated'))}</div><div class="trace-identity">${correlationMeta(anchor)}</div><div class="trace-steps">${group.steps.map(traceStep).join('')}</div></article>`}).join(''):'<div class="empty">尚無 tool / task / dispatch trace telemetry。</div>'}
function toolCard(x,compact=false){const direct=!x.taskId;return `<article class="flow-card tool-flow ${x.status==='running'?'live':''}"><div class="flow-head"><div><div class="route">Client / ChatGPT <span>→</span> MCP tool</div><h3>${esc(x.tool||'unknown tool')}</h3><p>${esc(short(toolDescription(x),compact?140:260))}</p></div>${badge(x.status)}</div><div class="meta"><span class="mono">request ${esc(x.requestId||'-')}</span><span>${esc(time(x.startedAt))}</span><span>${esc(x.durationMs==null?'執行中':x.durationMs+' ms')}</span></div><div class="correlation ${direct?'direct':''}">${direct?'直接 MCP 活動：telemetry 未提供 taskId / agentId，不推測對話關聯。':`關聯 task ${esc(x.taskId)}${x.agentId?' / agent '+esc(x.agentId):''}`}</div>${compact?'':invocationFields(x.parameters)}${x.error?`<div class="error-box">${esc(x.error)}</div>`:''}${compact?'':detail('原始 structured invocation JSON（telemetry parameters）',x.parameters||{})}</article>`}
function renderCurrentWork(){const tasks=arr(state.runtime.tasks).filter(x=>!terminal(x.status)&&x.status!=='unknown'),tools=arr(state.runtime.toolExecutions).filter(x=>x.status==='running');const items=[...tasks.map(x=>({kind:'task',at:x.updatedAt,item:x})),...tools.map(x=>({kind:'tool',at:x.startedAt,item:x}))].sort((a,b)=>String(b.at||'').localeCompare(String(a.at||'')));$('#currentCount').textContent=items.length;$('#currentWork').innerHTML=items.length?items.map(w=>w.kind==='tool'?toolCard(w.item,true):`<article class="work-card"><div class="work-top"><span class="kind">TASK</span>${badge(w.item.status)}</div><h3>${esc(w.item.objective||w.item.taskId||'未命名工作')}</h3><div class="meta"><span class="mono">${esc(w.item.taskId||'-')}</span><span>${esc(w.item.agent||w.item.agentId||'未指派')}</span><span>${esc(time(w.item.updatedAt))}</span></div><p>${esc(w.item.project||'-')} · ${esc(w.item.workingPath||w.item.sourcePath||'project root')}</p></article>`).join(''):'<div class="empty">目前沒有進行中的 task 或 MCP tool execution。</div>'}
function renderTools(){const items=[...arr(state.runtime.toolExecutions)].sort((a,b)=>String(b.startedAt||'').localeCompare(String(a.startedAt||''))).slice(0,100);$('#toolCount').textContent=items.length;$('#tools').innerHTML=items.length?items.map(x=>toolCard(x)).join(''):'<div class="empty">目前沒有 MCP tool telemetry。</div>'}
function renderRecent(){const tasks=arr(state.runtime.tasks).filter(x=>terminal(x.status)).map(x=>({kind:'Task',name:x.objective||x.taskId,status:x.status,at:x.updatedAt,id:x.taskId}));const tools=arr(state.runtime.toolExecutions).filter(x=>terminal(x.status)).map(x=>({kind:'MCP tool',name:x.tool,status:x.status,at:x.endedAt||x.startedAt,id:x.requestId}));const items=[...tasks,...tools].sort((a,b)=>String(b.at||'').localeCompare(String(a.at||''))).slice(0,80);$('#recentCount').textContent=items.length;$('#recentWork').innerHTML=items.length?items.map(x=>`<div class="compact-row"><span class="kind">${esc(x.kind)}</span><strong>${esc(short(x.name,150))}</strong>${badge(x.status)}<span class="mono muted">${esc(x.id||'-')}</span><time>${esc(time(x.at))}</time></div>`).join(''):'<div class="empty">尚無已完成工作。</div>'}
function renderDispatch(){const tasks=new Map(arr(state.runtime.tasks).map(t=>[String(t.taskId),t]));const items=[...arr(state.runtime.dispatches)].sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||''))).slice(0,100);$('#dispatchCount').textContent=items.length;$('#dispatches').innerHTML=items.length?items.map(d=>{const t={...(tasks.get(String(d.taskId))||{}),...d};return `<article class="flow-card dispatch-flow"><div class="flow-head"><div><div class="route">MCP / A0 <span>→</span> A2A Agent</div><h3>${esc(t.objective||t.taskId||'未命名 A2A 工作')}</h3><p>${esc(t.project||'-')} · ${esc(t.workingPath||'project root')}</p></div>${badge(d.status)}</div><div class="meta"><span class="mono">${esc(d.dispatchId||'-')}</span><span>target ${esc(d.toAgentId||d.agentId||'-')}</span><span>${esc(time(d.updatedAt))}</span></div><div class="scope-grid">${scope('Read scopes',t.readScopes)}${scope('Write scopes',t.writeScopes)}${scope('Acceptance criteria',t.acceptanceCriteria)}</div>${d.dispatchPrompt?detail('實際送出的 dispatch prompt',d.dispatchPrompt):'<div class="pending-note">尚未送出 prompt；等待初始化、cooldown 或 dispatch。</div>'}${detail('原始 dispatch telemetry JSON',d)}</article>`}).join(''):'<div class="empty">目前沒有 A2A dispatch telemetry。</div>'}
function renderTasks(){const items=[...arr(state.runtime.tasks)].sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));$('#taskCount').textContent=items.length;$('#tasks').innerHTML=items.length?items.map(t=>`<tr><td class="mono">${esc(t.taskId)}</td><td>${badge(t.status)}</td><td>${esc(t.agent||t.agentId||'-')}</td><td><div>${esc(t.project||'-')}</div><div class="muted">${esc(t.workingPath||t.sourcePath||'-')}</div></td><td>${esc(short(t.objective||'-'))}</td><td>${esc(time(t.updatedAt))}</td></tr>`).join(''):'<tr><td colspan="6" class="muted">目前沒有 task telemetry。</td></tr>'}
function renderAgents(){const items=[...arr(state.runtime.agents)].sort((a,b)=>String(a.agentId).localeCompare(String(b.agentId)));$('#agents').innerHTML=items.length?items.map(a=>`<article class="card"><div class="card-head"><div><div class="card-title">${esc(a.name||a.agentId)}</div><div class="card-sub mono">${esc(a.agentId)}</div></div>${badge(a.status)}</div><dl><dt>Type</dt><dd>${esc(a.type||'-')}</dd><dt>Backend</dt><dd>${esc(a.backend||'-')}</dd><dt>Task</dt><dd>${esc(a.currentTaskId||'-')}</dd><dt>Activity</dt><dd>${esc(time(a.lastActivityAt))}</dd></dl></article>`).join(''):'<div class="empty">目前沒有 Agent telemetry。</div>'}
function renderClaims(){const held=arr(state.runtime.claims).filter(x=>x.status!=='released').sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));$('#claims').innerHTML=held.length?held.map(c=>`<article class="card"><div class="card-head"><div><div class="card-title">${esc(c.resource||c.path||c.claimId)}</div><div class="card-sub">${esc(c.resourceType||'path')} / ${esc(c.mode||'exclusive')}</div></div>${badge(c.status)}</div><dl><dt>Owner</dt><dd>${esc(c.ownerAgentId||c.agent||'-')}</dd><dt>Task</dt><dd>${esc(c.taskId||'-')}</dd><dt>Updated</dt><dd>${esc(time(c.updatedAt||c.claimedAt))}</dd></dl></article>`).join(''):'<div class="empty">目前沒有持有中的 claim / mutex。</div>'}
function renderEvents(){const items=arr(state.events).map((event,index)=>({event,index,timestamp:Date.parse(event.timestamp)})).sort((a,b)=>{const aValid=Number.isFinite(a.timestamp),bValid=Number.isFinite(b.timestamp);if(aValid&&bValid&&a.timestamp!==b.timestamp)return b.timestamp-a.timestamp;if(aValid!==bValid)return aValid?-1:1;return a.index-b.index}).map(x=>x.event);$('#eventCount').textContent=items.length;$('#events').innerHTML=items.length?items.map(e=>`<div class="event ${e.severity==='error'?'error':''}"><span>${esc(time(e.timestamp).split(' ').pop())}</span><span class="type">${esc(e.type)}</span><span class="source">${esc(e.source)}</span><span class="data">${esc(short(JSON.stringify(e.data||{}),180))}</span></div>`).join(''):'<div class="event"><span>-</span><span class="type">no events</span><span></span><span>等待 telemetry event。</span></div>'}
function render(){summary();renderRuntimeHealth();renderTraces();renderCurrentWork();renderTools();renderRecent();renderDispatch();renderInfrastructure();renderTasks();renderAgents();renderClaims();renderEvents()}
chrome.webview.addEventListener('message',ev=>{const m=ev.data||{};if(m.type==='snapshot'){state.runtime=m.state||{};state.events=m.events||[];state.infra=m.infrastructure||null;state.auto=!!m.autoRefresh;$('#autoRefresh').checked=state.auto;const runtimeOk=!!m.stateExists;$('#connection').textContent=runtimeOk?'Runtime connected':'Waiting for telemetry';$('#connection').className='status-pill '+(runtimeOk?'ok':'off');$('#runtimePath').textContent=`${m.environment||'MAIN'} · ${m.runtimeRoot||''}`;$('#updatedAt').textContent='Snapshot '+time(m.generatedAt);render()}else if(m.type==='autoRefresh'){$('#autoRefresh').checked=!!m.enabled}else if(m.type==='error'){console.error(m.message);$('#connection').textContent='Error';$('#connection').className='status-pill off'}});
$('#refresh').addEventListener('click',()=>send('snapshot'));
$('#autoRefresh').addEventListener('change',e=>send('setAutoRefresh',{enabled:e.target.checked}));
send('snapshot');
})();
