(()=>{
const state={runtime:{tasks:[],agents:[],toolExecutions:[],claims:[],waits:[],dispatches:[]},events:[],auto:true};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const send=(action,payload={})=>chrome.webview.postMessage({action,...payload});
const arr=v=>Array.isArray(v)?v:[];
const time=v=>{if(!v)return'-';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('zh-TW',{hour12:false,month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'})};
const short=v=>String(v??'').length>90?String(v).slice(0,90)+'…':String(v??'');
const badge=s=>`<span class="badge ${esc(String(s||'unknown').toLowerCase())}">${esc(s||'unknown')}</span>`;
function summary(){const t=arr(state.runtime.tasks),a=arr(state.runtime.agents),x=arr(state.runtime.toolExecutions),c=arr(state.runtime.claims),w=arr(state.runtime.waits);const values=[['Agents',a.filter(x=>x.status!=='offline').length,''],['Busy',a.filter(x=>x.status==='busy').length,''],['Queued',t.filter(x=>x.status==='queued'||x.status==='assigned').length,'warn'],['Running',t.filter(x=>x.status==='running').length,''],['Active Tools',x.filter(x=>x.status==='running').length,''],['Claims',c.filter(x=>x.status==='held').length,'warn'],['Waiting',w.filter(x=>x.status==='waiting').length,'warn']];$('#summary').innerHTML=values.map(([k,v,cl])=>`<div class="metric ${cl}"><div class="metric-label">${k}</div><div class="metric-value">${v}</div></div>`).join('')}
function renderTasks(){const items=[...arr(state.runtime.tasks)].sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));$('#taskCount').textContent=items.length;$('#tasks').innerHTML=items.length?items.map(t=>`<tr><td class="mono">${esc(t.taskId)}</td><td>${badge(t.status)}</td><td>${esc(t.agent||t.agentId||'-')}</td><td><div>${esc(t.project||'-')}</div><div class="muted ellipsis">${esc(t.workingPath||t.sourcePath||'-')}</div></td><td class="ellipsis" title="${esc(t.objective||'')}">${esc(short(t.objective||'-'))}</td><td>${esc(time(t.updatedAt))}</td></tr>`).join(''):`<tr><td colspan="6" class="muted">目前沒有 task telemetry。</td></tr>`}
function renderAgents(){const items=[...arr(state.runtime.agents)].sort((a,b)=>String(a.agentId).localeCompare(String(b.agentId)));$('#agents').innerHTML=items.length?items.map(a=>`<article class="card"><div class="card-head"><div><div class="card-title">${esc(a.name||a.agentId)}</div><div class="card-sub mono">${esc(a.agentId)}</div></div>${badge(a.status)}</div><dl><dt>Type</dt><dd>${esc(a.type||'-')}</dd><dt>Backend</dt><dd>${esc(a.backend||'-')}</dd><dt>Task</dt><dd class="mono">${esc(a.currentTaskId||'-')}</dd><dt>Activity</dt><dd>${esc(time(a.lastActivityAt))}</dd></dl></article>`).join(''):`<div class="empty">目前沒有 Agent telemetry。</div>`}
function renderClaims(){const held=arr(state.runtime.claims).filter(x=>x.status!=='released').sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));$('#claims').innerHTML=held.length?held.map(c=>`<article class="card"><div class="card-head"><div><div class="card-title">${esc(c.resource||c.path||c.claimId)}</div><div class="card-sub">${esc(c.resourceType||'path')} / ${esc(c.mode||'exclusive')}</div></div>${badge(c.status)}</div><dl><dt>Owner</dt><dd>${esc(c.ownerAgentId||c.agent||'-')}</dd><dt>Task</dt><dd class="mono">${esc(c.taskId||'-')}</dd><dt>Updated</dt><dd>${esc(time(c.updatedAt||c.claimedAt))}</dd></dl></article>`).join(''):`<div class="empty">目前沒有持有中的 claim / mutex。</div>`}
function renderTools(){const items=[...arr(state.runtime.toolExecutions)].sort((a,b)=>String(b.startedAt||'').localeCompare(String(a.startedAt||''))).slice(0,120);$('#tools').innerHTML=items.length?items.map(x=>`<tr><td><strong>${esc(x.tool||'-')}</strong><div class="muted mono">${esc(x.requestId||'')}</div></td><td>${badge(x.status)}</td><td><div class="mono">${esc(x.taskId||'-')}</div><div class="muted">${esc(x.agentId||'-')}</div></td><td>${esc(x.durationMs==null?'-':x.durationMs+' ms')}</td><td>${esc(time(x.startedAt))}</td><td class="ellipsis" title="${esc(JSON.stringify(x.error||x.resultSummary||''))}">${esc(short(x.error||JSON.stringify(x.resultSummary||'')||'-'))}</td></tr>`).join(''):`<tr><td colspan="6" class="muted">目前沒有 Tool telemetry。</td></tr>`}
function renderDispatch(){const items=[...arr(state.runtime.dispatches)].sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||''))).slice(0,100);$('#dispatches').innerHTML=items.length?items.map(d=>`<tr><td class="mono">${esc(d.taskId||'-')}</td><td>${badge(d.status)}</td><td>${esc(d.fromAgentId||d.from||'-')}</td><td>${esc(d.toAgentId||d.to||d.agentId||'-')}</td><td>${esc(d.backend||'-')}</td><td>${esc(time(d.updatedAt))}</td></tr>`).join(''):`<tr><td colspan="6" class="muted">目前沒有 Dispatch telemetry。</td></tr>`}
function renderEvents(){const items=[...arr(state.events)].sort((a,b)=>(b.sequence||0)-(a.sequence||0));$('#eventCount').textContent=items.length;$('#events').innerHTML=items.length?items.map(e=>`<div class="event ${e.severity==='error'?'error':''}"><span>${esc(time(e.timestamp).split(' ').pop())}</span><span class="type">${esc(e.type)}</span><span class="source">${esc(e.source)}</span><span class="data">${esc(short(JSON.stringify(e.data||{})))}</span></div>`).join(''):`<div class="event"><span>-</span><span class="type">no events</span><span></span><span>等待 telemetry event。</span></div>`}
function render(){summary();renderTasks();renderAgents();renderClaims();renderTools();renderDispatch();renderEvents()}
chrome.webview.addEventListener('message',ev=>{const m=ev.data||{};if(m.type==='snapshot'){state.runtime=m.state||{};state.events=m.events||[];state.auto=!!m.autoRefresh;$('#autoRefresh').checked=state.auto;$('#connection').textContent=m.stateExists?'Runtime OK':'No state.json';$('#connection').className='status-pill '+(m.stateExists?'ok':'off');$('#runtimePath').textContent=m.runtimeRoot||'';$('#updatedAt').textContent='Snapshot '+time(m.generatedAt);render()}else if(m.type==='autoRefresh'){$('#autoRefresh').checked=!!m.enabled}else if(m.type==='error'){console.error(m.message);$('#connection').textContent='Error';$('#connection').className='status-pill off'}});
$('#refresh').addEventListener('click',()=>send('snapshot'));
$('#autoRefresh').addEventListener('change',e=>send('setAutoRefresh',{enabled:e.target.checked}));
send('snapshot');
})();
